/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/dev/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sign in as a synthetic development user
         * @description Issue a short-lived synthetic token.
         *
         *     The account must already exist and be flagged synthetic. This route never
         *     creates an account, so it cannot be used to mint a principal that the seeded
         *     development fixture did not define.
         */
        post: operations["development_login_api_v1_auth_dev_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/dev/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Synthetic users available for development sign-in
         * @description List the synthetic accounts a developer may sign in as.
         */
        get: operations["development_users_api_v1_auth_dev_users_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * End the current session
         * @description Record the logout.
         *
         *     Token revocation is the identity provider's responsibility; MARS records the
         *     event so the audit trail has both ends of the session.
         */
        post: operations["logout_api_v1_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The caller's profile and effective authorisation
         * @description Return the caller's own non-sensitive profile.
         *
         *     The frontend uses this to decide what to render. It is a convenience, not a
         *     control: every endpoint re-checks server-side, so a client that ignores this
         *     response gains nothing.
         */
        get: operations["current_user_api_v1_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/facilities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List facilities within your scope
         * @description List facilities.
         *
         *     Scope is applied in the query, so a district filter naming another district
         *     returns nothing rather than raising - a caller learns what they may see, not
         *     what exists elsewhere.
         */
        get: operations["list_facilities_api_v1_facilities_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/facilities/{facility_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One facility */
        get: operations["get_facility_api_v1_facilities__facility_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/geography/aliases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Resolve a source system's geography code
         * @description Return every candidate mapping for a source code.
         *
         *     More than one result means the mapping is ambiguous and needs review. MARS
         *     does not pick one: an ambiguous source value stays unresolved.
         */
        get: operations["resolve_alias_api_v1_geography_aliases_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/geography/boundary-versions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Registered boundary dataset versions */
        get: operations["list_boundary_versions_api_v1_geography_boundary_versions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/geography/districts/{code}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Look up a district by its code
         * @description Resolve a district code to a unit.
         *
         *     A code outside the caller's scope raises the same not-found as a code that
         *     was never issued.
         */
        get: operations["get_district_api_v1_geography_districts__code__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/geography/map/features": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Simplified boundary geometry for one level, as GeoJSON
         * @description Return one drawable layer.
         *
         *     parent_id selects direct children; within_id selects every descendant
         *     at the requested level, which is how a district drills to its subcounties -
         *     those hang off counties, so a parent filter would return nothing.
         *
         *     Always simplified: full-resolution geometry is the analytical copy and never
         *     leaves the server. A request matching more units than the ceiling allows is
         *     refused with 413 rather than truncated, because a partial map that looks
         *     complete is worse than an error.
         *
         *     The response carries a strong ETag derived from the boundary version and the
         *     query, so a client re-opening the national view revalidates in a few bytes.
         *     A matching ``If-None-Match`` returns 304.
         */
        get: operations["map_features_api_v1_geography_map_features_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/geography/map/metadata": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * What this caller can draw, and from which boundary version
         * @description Describe the drawable geography before any geometry is fetched.
         *
         *     One request, deliberately: a client that needs several calls to learn which
         *     boundary version it is drawing will eventually draw two at once.
         */
        get: operations["map_metadata_api_v1_geography_map_metadata_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/geography/national": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The caller's root geography and the level below it
         * @description Open the map at the top of the caller's scope.
         *
         *     "National" means the highest unit this caller can see, which for a district
         *     account is their district. Deriving it from scope rather than assuming
         *     Uganda means a delegated account opens correctly with no special case in the
         *     client.
         */
        get: operations["national_geography_api_v1_geography_national_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/geography/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Hierarchy metadata and loaded boundary versions
         * @description Report unit counts per level and the boundary versions registered.
         *
         *     Levels with no data are reported as zero rather than omitted, so an empty
         *     parish level reads as "none loaded" and not as "level not supported".
         */
        get: operations["overview_api_v1_geography_overview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/geography/subcounties/{code}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Look up a subcounty by its code */
        get: operations["get_subcounty_api_v1_geography_subcounties__code__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/geography/units": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List geography units within your scope */
        get: operations["list_units_api_v1_geography_units_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/geography/units/{unit_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One geography unit, with its ancestor chain */
        get: operations["get_unit_api_v1_geography_units__unit_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/geography/units/{unit_id}/bounds": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * One unit's extent, without transferring its geometry
         * @description Four numbers, so a client can zoom to a district without downloading it.
         */
        get: operations["unit_bounds_api_v1_geography_units__unit_id__bounds_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/geography/units/{unit_id}/breadcrumbs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The ancestor chain from the caller's root down to this unit
         * @description Country / region / district / subcounty, ending with the unit itself.
         *
         *     Only ancestors the caller may see appear, so a district user's trail starts
         *     at the highest unit in their scope rather than revealing the chain above it.
         */
        get: operations["unit_breadcrumbs_api_v1_geography_units__unit_id__breadcrumbs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/geography/units/{unit_id}/children": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Direct children of a geography unit */
        get: operations["get_children_api_v1_geography_units__unit_id__children_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/geography/units/{unit_id}/geometry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One unit's simplified boundary, as a GeoJSON Feature */
        get: operations["unit_geometry_api_v1_geography_units__unit_id__geometry_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/governance/configuration-keys": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Governed configuration keys and which version is active
         * @description List configuration keys.
         *
         *     A key with no active version is returned with nulls rather than omitted: an
         *     ungoverned parameter is a fact the programme needs to see.
         */
        get: operations["list_configuration_keys_api_v1_governance_configuration_keys_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/governance/methods": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The analytical method registry
         * @description List registered methods and their versions.
         *
         *     Empty until Prompt 13. An empty registry is the honest state: no analytical
         *     method has been defined, let alone validated or approved.
         */
        get: operations["list_methods_api_v1_governance_methods_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness probe
         * @description Return 200 whenever the process is able to serve a request.
         */
        get: operations["liveness_api_v1_health_live_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readiness probe
         * @description Check backing services and report each one individually.
         *
         *     PostGIS absence is reported as ``not_installed`` and makes the service
         *     unready. Migration ``0003_phase2_hardening`` introduced PostGIS geometry
         *     columns, so the current schema head cannot be applied without the extension.
         */
        get: operations["readiness_api_v1_health_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health/schema": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Report which MARS schemas exist
         * @description List the MARS schemas present in the connected database.
         *
         *     Used by the development shell and by deployment smoke checks to confirm that
         *     migrations have been applied.
         */
        get: operations["schema_state_api_v1_health_schema_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/meta/evidence-lanes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * How MARS separates routine signals from confirmed findings
         * @description Describe the two-lane evidence model.
         *
         *     Served by the API rather than written into the interface so that the
         *     scientific boundary has one authoritative statement, used identically by the
         *     dashboard, generated reports and documentation.
         */
        get: operations["evidence_lanes_api_v1_meta_evidence_lanes_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/meta/permissions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The permission catalogue this build recognises
         * @description Describe every permission and the sensitivity tier it requires.
         *
         *     Read by the administration interface so that permission descriptions come
         *     from one place rather than being re-typed in the frontend.
         */
        get: operations["permission_catalogue_api_v1_meta_permissions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/meta/version": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Build and governance identity of this deployment
         * @description Return build identity plus the active method and configuration registry.
         *
         *     Registry lookups are best-effort: this endpoint must keep answering during a
         *     database outage, because it is what an operator reaches for first when
         *     something is wrong.
         */
        get: operations["version_api_v1_meta_version_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organisation-units": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List organisation units within your scope
         * @description List health-sector organisation units.
         *
         *     Health Sub-District is one of the unit types here, not a geography level:
         *     MARS does not assume an HSD coincides with a county.
         */
        get: operations["list_organisation_units_api_v1_organisation_units_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organisation-units/{unit_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One organisation unit, with its ancestor chain */
        get: operations["get_organisation_unit_api_v1_organisation_units__unit_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** BoundaryVersionSummary */
        BoundaryVersionSummary: {
            /** Code */
            code: string;
            /** Effective From */
            effective_from: string | null;
            /** Effective To */
            effective_to: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Import Status */
            import_status: string;
            /** Label */
            label: string;
            /** Source Checksum */
            source_checksum: string | null;
            /** Source Crs */
            source_crs: string | null;
            /** Source File Name */
            source_file_name: string | null;
            /** Source Format */
            source_format: string | null;
            /** Source Name */
            source_name: string;
            /** Storage Crs */
            storage_crs: string;
            /** Validation Summary */
            validation_summary: {
                [key: string]: unknown;
            } | null;
        };
        /**
         * BoundingBoxModel
         * @description A geographic extent in EPSG:4326 degrees, west/south/east/north.
         */
        BoundingBoxModel: {
            /** Max Lat */
            max_lat: number;
            /** Max Lon */
            max_lon: number;
            /** Min Lat */
            min_lat: number;
            /** Min Lon */
            min_lon: number;
        };
        /** ConfigurationKeySummary */
        ConfigurationKeySummary: {
            /** Active Effective From */
            active_effective_from: string | null;
            /** Active Version Checksum */
            active_version_checksum: string | null;
            /** Active Version Number */
            active_version_number: number | null;
            /** Category */
            category: string;
            /** Description */
            description: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Key */
            key: string;
            /** Label */
            label: string;
            /** Requires Programme Approval */
            requires_programme_approval: boolean;
        };
        /**
         * CurrentUserResponse
         * @description The caller's own non-sensitive profile and effective authorisation.
         */
        CurrentUserResponse: {
            /** Auth Method */
            auth_method: string;
            /** Display Name */
            display_name: string;
            /** Email */
            email: string | null;
            /** Facility Scope Ids */
            facility_scope_ids: string[];
            /** Geography Scopes */
            geography_scopes: components["schemas"]["GeographyScopeSummary"][];
            /** Has National Scope */
            has_national_scope: boolean;
            /**
             * Is Synthetic
             * @description True for development accounts. The interface must mark these visibly.
             */
            is_synthetic: boolean;
            /** Max Sensitivity */
            max_sensitivity: string;
            /** Organisation Label */
            organisation_label: string | null;
            /** Permissions */
            permissions: string[];
            /** Roles */
            roles: string[];
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
            /** Username */
            username: string;
        };
        /** DependencyStatus */
        DependencyStatus: {
            /** Detail */
            detail?: string | null;
            /** Name */
            name: string;
            /**
             * Status
             * @description ok | unavailable | not_installed
             */
            status: string;
            /** Version */
            version?: string | null;
        };
        /**
         * DevelopmentLoginRequest
         * @description Request a synthetic development token. Non-production only.
         */
        DevelopmentLoginRequest: {
            /** Username */
            username: string;
        };
        /** DevelopmentLoginResponse */
        DevelopmentLoginResponse: {
            /** Access Token */
            access_token: string;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
            /**
             * Warning
             * @default Synthetic development session. Not valid in staging or production.
             */
            warning: string;
        };
        /**
         * DevelopmentUserSummary
         * @description A selectable synthetic user, for the development sign-in screen.
         */
        DevelopmentUserSummary: {
            /** Display Name */
            display_name: string;
            /** Role */
            role: string;
            /** Scope Description */
            scope_description: string;
            /** Username */
            username: string;
        };
        /** FacilityDetail */
        FacilityDetail: {
            /** Closed On */
            closed_on: string | null;
            /** Code */
            code: string;
            /** Coordinate Source */
            coordinate_source: string | null;
            /** Coordinate Validated */
            coordinate_validated: boolean;
            /** District Geography Unit Id */
            district_geography_unit_id: string | null;
            /** Facility Level */
            facility_level: string;
            /**
             * Has Coordinates
             * @description True only when a validated coordinate exists. MARS never places a facility approximately.
             */
            has_coordinates: boolean;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Identifiers */
            identifiers?: components["schemas"]["FacilityIdentifierSummary"][];
            /** Is Active */
            is_active: boolean;
            /** Is Synthetic */
            is_synthetic: boolean;
            /** Name */
            name: string;
            /** Opened On */
            opened_on: string | null;
            /** Organisation Unit Id */
            organisation_unit_id: string | null;
            /** Ownership */
            ownership: string;
            /** Subcounty Geography Unit Id */
            subcounty_geography_unit_id: string | null;
        };
        /** FacilityIdentifierSummary */
        FacilityIdentifierSummary: {
            /** External Id */
            external_id: string;
            /** External Name */
            external_name: string | null;
            /** Is Primary */
            is_primary: boolean;
            /** Source System */
            source_system: string;
        };
        /**
         * FacilityLevel
         * @description Uganda health facility levels.
         *
         *     Values follow the national facility-level nomenclature. The authoritative
         *     assignment for any given facility comes from the facility master, which has
         *     not yet been supplied; ``unknown`` is the honest default.
         * @enum {string}
         */
        FacilityLevel: "unknown" | "hc_ii" | "hc_iii" | "hc_iv" | "general_hospital" | "regional_referral_hospital" | "national_referral_hospital" | "specialised_clinic";
        /** FacilitySummary */
        FacilitySummary: {
            /** Code */
            code: string;
            /** District Geography Unit Id */
            district_geography_unit_id: string | null;
            /** Facility Level */
            facility_level: string;
            /**
             * Has Coordinates
             * @description True only when a validated coordinate exists. MARS never places a facility approximately.
             */
            has_coordinates: boolean;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Is Active */
            is_active: boolean;
            /** Is Synthetic */
            is_synthetic: boolean;
            /** Name */
            name: string;
            /** Organisation Unit Id */
            organisation_unit_id: string | null;
            /** Ownership */
            ownership: string;
            /** Subcounty Geography Unit Id */
            subcounty_geography_unit_id: string | null;
        };
        /**
         * FieldError
         * @description A single field-level validation failure.
         */
        FieldError: {
            /** Code */
            code?: string | null;
            /** Field */
            field: string;
            /** Message */
            message: string;
        };
        /** GeographyAliasSummary */
        GeographyAliasSummary: {
            /**
             * Geography Unit Id
             * Format: uuid
             */
            geography_unit_id: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Match Method */
            match_method: string | null;
            /** Match Status */
            match_status: string;
            /** Source Code */
            source_code: string;
            /** Source Name */
            source_name: string | null;
            /** Source System */
            source_system: string;
        };
        /**
         * GeographyBreadcrumb
         * @description One step in the ancestor chain, from country down to the unit.
         */
        GeographyBreadcrumb: {
            /** Code */
            code: string;
            /** Is Current */
            is_current: boolean;
            /** Level */
            level: string;
            /** Name */
            name: string;
            /**
             * Unit Id
             * Format: uuid
             */
            unit_id: string;
        };
        /** GeographyBreadcrumbsResponse */
        GeographyBreadcrumbsResponse: {
            /** Breadcrumbs */
            breadcrumbs: components["schemas"]["GeographyBreadcrumb"][];
        };
        /**
         * GeographyLevel
         * @description Administrative hierarchy levels.
         *
         *     All seven levels exist in the schema from the outset. Parish and village are
         *     defined but will remain empty: no parish or village boundary data has been
         *     supplied, and MARS does not fabricate geography.
         * @enum {string}
         */
        GeographyLevel: "country" | "region" | "district" | "county" | "subcounty" | "parish" | "village";
        /** GeographyLevelCount */
        GeographyLevelCount: {
            /** Count */
            count: number;
            /** Level */
            level: string;
        };
        /**
         * GeographyOverviewResponse
         * @description Hierarchy metadata, including levels that are deliberately empty.
         */
        GeographyOverviewResponse: {
            /** Boundary Versions */
            boundary_versions: components["schemas"]["BoundaryVersionSummary"][];
            /** Levels */
            levels: components["schemas"]["GeographyLevelCount"][];
            /** Note */
            note: string;
        };
        /** GeographyScopeSummary */
        GeographyScopeSummary: {
            /**
             * Geography Unit Id
             * Format: uuid
             */
            geography_unit_id: string;
            /** Level */
            level: string;
            /** Name */
            name: string;
            /** Preferred Code */
            preferred_code: string;
        };
        /** GeographyUnitDetail */
        GeographyUnitDetail: {
            /** Ancestors */
            ancestors?: components["schemas"]["GeographyUnitSummary"][];
            /** Boundary Version Id */
            boundary_version_id: string | null;
            /**
             * Child Count
             * @default 0
             */
            child_count: number;
            /** Depth */
            depth: number;
            /** Effective From */
            effective_from: string | null;
            /** Effective To */
            effective_to: string | null;
            /**
             * Has Geometry
             * @description False throughout phases 1-2; geometry is imported in Prompt 5.
             * @default false
             */
            has_geometry: boolean;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Is Active */
            is_active: boolean;
            /** Level */
            level: string;
            /**
             * Name
             * @description The raw supplied name. Displayed as-is.
             */
            name: string;
            /**
             * Normalised Name
             * @description Lookup form. Not for display.
             */
            normalised_name: string;
            /** Parent Id */
            parent_id: string | null;
            /** Path */
            path: string | null;
            /** Preferred Code */
            preferred_code: string;
            /** Unit Kind */
            unit_kind: string;
        };
        /** GeographyUnitSummary */
        GeographyUnitSummary: {
            /** Depth */
            depth: number;
            /** Effective From */
            effective_from: string | null;
            /** Effective To */
            effective_to: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Is Active */
            is_active: boolean;
            /** Level */
            level: string;
            /**
             * Name
             * @description The raw supplied name. Displayed as-is.
             */
            name: string;
            /**
             * Normalised Name
             * @description Lookup form. Not for display.
             */
            normalised_name: string;
            /** Parent Id */
            parent_id: string | null;
            /** Path */
            path: string | null;
            /** Preferred Code */
            preferred_code: string;
            /** Unit Kind */
            unit_kind: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LivenessResponse */
        LivenessResponse: {
            /** Service */
            service: string;
            /**
             * Status
             * @description Always 'alive' when the process is serving.
             */
            status: string;
        };
        /**
         * MapCollectionMeta
         * @description MARS metadata carried inside the FeatureCollection as a foreign member.
         */
        MapCollectionMeta: {
            /** Boundary Version Code */
            boundary_version_code: string | null;
            /** Boundary Version Id */
            boundary_version_id: string | null;
            /** Feature Count */
            feature_count: number;
            /** Geometry Resolution */
            geometry_resolution: string;
            /** Level */
            level: string | null;
            /** Matched Count */
            matched_count: number;
            /** Parent Id */
            parent_id: string | null;
            /** Truncated */
            truncated: boolean;
            /** Within Id */
            within_id: string | null;
        };
        /**
         * MapFeature
         * @description One administrative area as GeoJSON.
         */
        MapFeature: {
            /**
             * Geometry
             * @description GeoJSON MultiPolygon, simplified for display.
             */
            geometry: {
                [key: string]: unknown;
            };
            /** Id */
            id: string;
            properties: components["schemas"]["MapFeatureProperties"];
            /**
             * Type
             * @default Feature
             */
            type: string;
        };
        /**
         * MapFeatureCollection
         * @description A GeoJSON FeatureCollection with the boundary version attached.
         *
         *     The version travels inside the document, not only in a header, so a saved
         *     or forwarded response still says which boundaries produced it.
         */
        MapFeatureCollection: {
            /**
             * Bbox
             * @description Extent of the whole collection: west, south, east, north.
             */
            bbox?: number[] | null;
            /** Features */
            features: components["schemas"]["MapFeature"][];
            mars: components["schemas"]["MapCollectionMeta"];
            /**
             * Type
             * @default FeatureCollection
             */
            type: string;
        };
        /**
         * MapFeatureProperties
         * @description The complete set of properties a map feature carries.
         *
         *     Declared as a closed model rather than a free-form object so the allow-list
         *     is part of the published contract and appears in the generated client.
         */
        MapFeatureProperties: {
            /** Area Sq Km */
            area_sq_km: number | null;
            /** Code */
            code: string;
            /** Is Active */
            is_active: boolean;
            /** Level */
            level: string;
            /** Name */
            name: string;
            /** Parent Id */
            parent_id: string | null;
            /** Path */
            path: string;
            /**
             * Unit Id
             * Format: uuid
             */
            unit_id: string;
        };
        /**
         * MapLevelAvailability
         * @description Whether one hierarchy level can be drawn, and at what tolerance.
         */
        MapLevelAvailability: {
            /** Geometry Count */
            geometry_count: number;
            /**
             * Is Drawable
             * @description False when the level exists in the schema but no geometry is loaded.
             */
            is_drawable: boolean;
            /** Level */
            level: string;
            /** Simplification Tolerance Deg */
            simplification_tolerance_deg: number | null;
            /**
             * Supports National Layer
             * @description Whether the whole level may be requested without a parent filter.
             */
            supports_national_layer: boolean;
            /** Unit Count */
            unit_count: number;
        };
        /**
         * MapMetadataResponse
         * @description What the caller may draw, and from which boundary version.
         *
         *     ``is_available`` false means no boundary version is published or none of
         *     its levels carry geometry. The client shows an explicit "no boundaries
         *     loaded" state rather than an empty canvas, which would read as a rendering
         *     failure.
         */
        MapMetadataResponse: {
            /** Boundary Version Code */
            boundary_version_code: string | null;
            /** Boundary Version Id */
            boundary_version_id: string | null;
            /** Boundary Version Label */
            boundary_version_label: string | null;
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
            /**
             * Geometry Resolution
             * @description Always 'simplified'. Full-resolution geometry is never served to a browser.
             */
            geometry_resolution: string;
            /** Imported At */
            imported_at: string | null;
            /** @description Extent of the highest unit in the caller's scope, for the first viewport. */
            initial_bounds: components["schemas"]["BoundingBoxModel"] | null;
            /** Initial Unit Id */
            initial_unit_id: string | null;
            /** Initial Unit Level */
            initial_unit_level: string | null;
            /** Initial Unit Name */
            initial_unit_name: string | null;
            /** Is Available */
            is_available: boolean;
            /** Levels */
            levels: components["schemas"]["MapLevelAvailability"][];
            /** Max Features */
            max_features: number;
            /**
             * Source Checksum
             * @description SHA-256 of the source set, so a client can prove which bytes it is drawing.
             */
            source_checksum: string | null;
            /** Source Name */
            source_name: string | null;
        };
        /** MethodDefinitionSummary */
        MethodDefinitionSummary: {
            /** Code */
            code: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Kind */
            kind: string;
            /** Label */
            label: string;
            /** Purpose */
            purpose: string;
            /** Versions */
            versions?: components["schemas"]["MethodVersionSummary"][];
        };
        /** MethodVersionSummary */
        MethodVersionSummary: {
            /** Artifact Checksum */
            artifact_checksum: string | null;
            /** Effective From */
            effective_from: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Semantic Version */
            semantic_version: string;
            /** Status */
            status: string;
            /** Summary */
            summary: string;
            /** Validation Reference */
            validation_reference: string | null;
        };
        /**
         * NationalGeographyResponse
         * @description The caller's root geography and the level below it.
         *
         *     "National" is the top of the caller's scope, not necessarily Uganda: a
         *     district user's national view is their district. The map opens correctly for
         *     a delegated account without a special case in the client.
         */
        NationalGeographyResponse: {
            /** Boundary Version Code */
            boundary_version_code: string | null;
            /** Boundary Version Id */
            boundary_version_id: string | null;
            bounds: components["schemas"]["BoundingBoxModel"] | null;
            /** Child Level */
            child_level: string | null;
            /** Children */
            children: components["schemas"]["GeographyUnitSummary"][];
            root: components["schemas"]["GeographyUnitSummary"] | null;
        };
        /** OrganisationUnitDetail */
        OrganisationUnitDetail: {
            /** Ancestors */
            ancestors?: components["schemas"]["OrganisationUnitSummary"][];
            /**
             * Child Count
             * @default 0
             */
            child_count: number;
            /** Code */
            code: string;
            /** Depth */
            depth: number;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Is Active */
            is_active: boolean;
            /** Name */
            name: string;
            /** Parent Id */
            parent_id: string | null;
            /** Primary Geography Unit Id */
            primary_geography_unit_id: string | null;
            /** Unit Type */
            unit_type: string;
        };
        /** OrganisationUnitSummary */
        OrganisationUnitSummary: {
            /** Code */
            code: string;
            /** Depth */
            depth: number;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Is Active */
            is_active: boolean;
            /** Name */
            name: string;
            /** Parent Id */
            parent_id: string | null;
            /** Primary Geography Unit Id */
            primary_geography_unit_id: string | null;
            /** Unit Type */
            unit_type: string;
        };
        /**
         * OrganisationUnitType
         * @description Health-sector organisational hierarchy.
         *
         *     Deliberately distinct from ``GeographyLevel``. A Health Sub-District is a
         *     health-sector management unit; it is not equivalent to a county, and MARS
         *     must not assume it is. The correspondence, where one exists, is recorded as
         *     data once the Ministry list is supplied.
         * @enum {string}
         */
        OrganisationUnitType: "national" | "regional_referral" | "district_health_office" | "health_sub_district" | "facility";
        /** Page[FacilitySummary] */
        Page_FacilitySummary_: {
            /** Items */
            items: components["schemas"]["FacilitySummary"][];
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /**
             * Total
             * @description Omitted when counting would be costly.
             */
            total?: number | null;
        };
        /** Page[GeographyUnitSummary] */
        Page_GeographyUnitSummary_: {
            /** Items */
            items: components["schemas"]["GeographyUnitSummary"][];
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /**
             * Total
             * @description Omitted when counting would be costly.
             */
            total?: number | null;
        };
        /** Page[OrganisationUnitSummary] */
        Page_OrganisationUnitSummary_: {
            /** Items */
            items: components["schemas"]["OrganisationUnitSummary"][];
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /**
             * Total
             * @description Omitted when counting would be costly.
             */
            total?: number | null;
        };
        /**
         * ProblemDetail
         * @description RFC 7807 problem document, extended with MARS diagnostics.
         */
        ProblemDetail: {
            /**
             * Code
             * @description Stable machine-readable MARS error code.
             */
            code: string;
            /**
             * Detail
             * @description Human-readable explanation.
             */
            detail?: string | null;
            /**
             * Documentation
             * @description Where to read more.
             */
            documentation?: string | null;
            /**
             * Errors
             * @description Field-level failures.
             */
            errors?: components["schemas"]["FieldError"][] | null;
            /**
             * Instance
             * @description Request path.
             */
            instance?: string | null;
            /**
             * Request Id
             * @description Correlates with server logs.
             */
            request_id?: string | null;
            /**
             * Status
             * @description HTTP status code.
             */
            status: number;
            /**
             * Title
             * @description Short, human-readable summary.
             */
            title: string;
            /**
             * Type
             * @description URI reference identifying the problem type.
             */
            type: string;
        };
        /** ReadinessResponse */
        ReadinessResponse: {
            /**
             * Checked At
             * Format: date-time
             */
            checked_at: string;
            /** Dependencies */
            dependencies: components["schemas"]["DependencyStatus"][];
            /**
             * Status
             * @description ready | degraded | unavailable
             */
            status: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /**
         * VersionResponse
         * @description Build and governance identity of this deployment.
         *
         *     Exposes which method versions are active, so a number on a screen can be
         *     traced to the rules that produced it. Configuration *content* is not
         *     exposed here - only which version is in force.
         */
        VersionResponse: {
            /**
             * Active Configuration Keys
             * @description Keys with an active version. Values are not exposed here.
             */
            active_configuration_keys?: string[];
            /**
             * Active Method Versions
             * @description Qualified identifiers, e.g. 'IND-TPR@1.2.0'. Empty until Prompt 13.
             */
            active_method_versions?: string[];
            /** Ai Assistant Enabled */
            ai_assistant_enabled: boolean;
            /** Api Version */
            api_version: string;
            /** Build Timestamp */
            build_timestamp: string | null;
            /** Demo Mode Enabled */
            demo_mode_enabled: boolean;
            /** Development Auth Active */
            development_auth_active: boolean;
            /** Display Timezone */
            display_timezone: string;
            /** Environment */
            environment: string;
            /** Git Sha */
            git_sha: string;
            /** Name */
            name: string;
            /** Release Version */
            release_version: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    development_login_api_v1_auth_dev_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DevelopmentLoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DevelopmentLoginResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    development_users_api_v1_auth_dev_users_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DevelopmentUserSummary"][];
                };
            };
        };
    };
    logout_api_v1_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    current_user_api_v1_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CurrentUserResponse"];
                };
            };
        };
    };
    list_facilities_api_v1_facilities_get: {
        parameters: {
            query?: {
                district_id?: string | null;
                subcounty_id?: string | null;
                organisation_unit_id?: string | null;
                facility_level?: components["schemas"]["FacilityLevel"] | null;
                active_only?: boolean;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_FacilitySummary_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_facility_api_v1_facilities__facility_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                facility_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FacilityDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resolve_alias_api_v1_geography_aliases_get: {
        parameters: {
            query: {
                /** @description e.g. ubos_fscode, dhis2 */
                source_system: string;
                source_code: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GeographyAliasSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_boundary_versions_api_v1_geography_boundary_versions_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BoundaryVersionSummary"][];
                };
            };
        };
    };
    get_district_api_v1_geography_districts__code__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GeographyUnitDetail"];
                };
            };
            /** @description The caller does not hold `geography:view`. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description No such unit, or the unit is outside the caller's geography scope. These are the same response by design. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    map_features_api_v1_geography_map_features_get: {
        parameters: {
            query: {
                /** @description Hierarchy level to draw */
                level: components["schemas"]["GeographyLevel"];
                /** @description Restrict to direct children of this unit */
                parent_id?: string | null;
                /** @description Restrict to any descendant of this unit at the requested level */
                within_id?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MapFeatureCollection"];
                };
            };
            /** @description The caller does not hold `geography:view`. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description No such unit, or the unit is outside the caller's geography scope. These are the same response by design. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description More features match than the payload ceiling allows. The request is refused rather than truncated; narrow it with `parent_id` or `within_id`. */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    map_metadata_api_v1_geography_map_metadata_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MapMetadataResponse"];
                };
            };
            /** @description The caller does not hold `geography:view`. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    national_geography_api_v1_geography_national_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NationalGeographyResponse"];
                };
            };
            /** @description The caller does not hold `geography:view`. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    overview_api_v1_geography_overview_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GeographyOverviewResponse"];
                };
            };
        };
    };
    get_subcounty_api_v1_geography_subcounties__code__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GeographyUnitDetail"];
                };
            };
            /** @description The caller does not hold `geography:view`. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description No such unit, or the unit is outside the caller's geography scope. These are the same response by design. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_units_api_v1_geography_units_get: {
        parameters: {
            query?: {
                /** @description Filter by hierarchy level */
                level?: components["schemas"]["GeographyLevel"] | null;
                /** @description Direct children of this unit */
                parent_id?: string | null;
                active_only?: boolean;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_GeographyUnitSummary_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_unit_api_v1_geography_units__unit_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                unit_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GeographyUnitDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    unit_bounds_api_v1_geography_units__unit_id__bounds_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                unit_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BoundingBoxModel"];
                };
            };
            /** @description The caller does not hold `geography:view`. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description No such unit, or the unit is outside the caller's geography scope. These are the same response by design. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    unit_breadcrumbs_api_v1_geography_units__unit_id__breadcrumbs_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                unit_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GeographyBreadcrumbsResponse"];
                };
            };
            /** @description The caller does not hold `geography:view`. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description No such unit, or the unit is outside the caller's geography scope. These are the same response by design. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_children_api_v1_geography_units__unit_id__children_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                unit_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GeographyUnitSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    unit_geometry_api_v1_geography_units__unit_id__geometry_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                unit_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MapFeature"];
                };
            };
            /** @description The caller does not hold `geography:view`. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description No such unit, or the unit is outside the caller's geography scope. These are the same response by design. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_configuration_keys_api_v1_governance_configuration_keys_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigurationKeySummary"][];
                };
            };
        };
    };
    list_methods_api_v1_governance_methods_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MethodDefinitionSummary"][];
                };
            };
        };
    };
    liveness_api_v1_health_live_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LivenessResponse"];
                };
            };
        };
    };
    readiness_api_v1_health_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadinessResponse"];
                };
            };
            /** @description A required dependency is unavailable. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    schema_state_api_v1_health_schema_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description The database could not be reached. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    evidence_lanes_api_v1_meta_evidence_lanes_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    permission_catalogue_api_v1_meta_permissions_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    version_api_v1_meta_version_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VersionResponse"];
                };
            };
        };
    };
    list_organisation_units_api_v1_organisation_units_get: {
        parameters: {
            query?: {
                unit_type?: components["schemas"]["OrganisationUnitType"] | null;
                parent_id?: string | null;
                active_only?: boolean;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_OrganisationUnitSummary_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_organisation_unit_api_v1_organisation_units__unit_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                unit_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrganisationUnitDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
